### ISSUE TITLE
global name 'Raw' is not defined

### ISSUE THREAD

**Issue by Nik100** [Vladimir-Ivanov-Git/raw-packet#1]
Добрый вечер. Не могу запустить...
sudo ./dhcp_starvation.py -i wlo1
[*] Sniffing interface: wlo1
[*] Sending discover packets...
[*] Delay between DISCOVER packets: 1 sec.
[*] Start sending packets: 2017/10/29 21:07:05
global name 'Raw' is not defined
 И после этого ничего не происходит. Что может быть?

**Comment by Nik100** [comment]
Забыл, вот такое предупреждение еще.
WARNING: No route found for IPv6 destination :: (no default route?)

**Comment by Nik100** [comment]
Это у меня не работает в Ubuntu и Raspberry. А в Kali все запустилось и даже получилось в итоге. Я, так понимаю, у меня в Ubuntu не определена глобальная переменная Raw. Верно?

**Comment by Vladimir-Ivanov-Git** [comment]
Я сейчас немного занят с CVE для DNSMASQ как освобожусь сразу вам отвечу и напишу вспомогательные фильтры что бы такой ошибки не было. Хорошо?

**Comment by Nik100** [comment]
Да, конечно, в любое удобное для Вас время! Интересно все работает, и статья на Хабре очень познавательная. Спасибо за проделанный труд...

**Comment by Vladimir-Ivanov-Git** [comment]
Вам спасибо.

**Comment by Vladimir-Ivanov-Git** [comment]
Привет!
Во первых необходимо установить все зависимости: $ pip install -r requirements.txt
Это сделано ?

**Comment by Nik100** [comment]
Привет. "$ pip install -r requirements.txt" сделано не было. Выполнил.
"global name 'Raw' is not defined" сохранилось.
Установка зависимостей прошла:

The directory '/home/gaz/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/gaz/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: netifaces>=0.10.5 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Collecting ipaddress>=1.0.18 (from -r requirements.txt (line 2))
  Downloading ipaddress-1.0.18-py2-none-any.whl
Collecting netaddr>=0.7.18 (from -r requirements.txt (line 3))
  Downloading netaddr-0.7.19-py2.py3-none-any.whl (1.6MB)
    100% |в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€| 1.6MB 45kB/s 
Collecting scapy>=2.3.1 (from -r requirements.txt (line 4))
  Downloading scapy-2.3.3.tgz (1.4MB)
    100% |в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€в–€| 1.4MB 23kB/s 
Installing collected packages: ipaddress, netaddr, scapy
  Found existing installation: ipaddress 1.0.14
    Uninstalling ipaddress-1.0.14:
      Successfully uninstalled ipaddress-1.0.14
  Found existing installation: scapy 2.2.0
    **DEPRECATION: Uninstalling a distutils installed project (scapy) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.**
    Uninstalling scapy-2.2.0:
      Successfully uninstalled scapy-2.2.0
  Running setup.py install for scapy ... done
Successfully installed ipaddress-1.0.18 netaddr-0.7.19 scapy-2.3.

**Comment by Vladimir-Ivanov-Git** [comment]
Можете скинуть все что пишет скрипт.

**Comment by Vladimir-Ivanov-Git** [comment]
И на Kali все сработало пул IP-адресов забился ?

**Comment by Nik100** [comment]
В Kali все сработало (что описано в ваших статьях), и по apple в том числе. Пул IP роутера, разумеется, забился. А вот raspbian и Ubuntu не хотят.
Выполняю скрипт:
pi@raspberrypi:~ $ cd raw-packet/
pi@raspberrypi:~/raw-packet $ sudo ./dhcp_starvation.py -i wlan0
WARNING: No route found for IPv6 destination :: (no default route?)
                                          _        _
 _ __ __ ___      __     _ __   __ _  ___| | _____| |_
| '__/ _` \ \ /\ / /___ | '_ \ / _` |/ __| |/ / _ \ __|
| | | (_| |\ V  V /|___|| |_) | (_| | (__|   <  __/ |_
|_|  \__,_| \_/\_/      | .__/ \__,_|\___|_|\_\___|\__|
                        |_|                      v0.0.3

https://github.com/Vladimir-Ivanov-Git/raw-packet

[*] Sniffing interface: wlan0
[*] Sending discover packets...
[*] Delay between DISCOVER packets: 1 sec.
[*] Start sending packets: 2017/11/24 20:44:22
global name 'Raw' is not defined
... и тишина, на роутере ничего не изменяется.
