### ISSUE TITLE
Need for MAC

### ISSUE THREAD

**Issue by hackituria** [Vladimir-Ivanov-Git/raw-packet#2]
I am using a VPN tunnel with a vulnerable Dnsmasq and when I want use dnsmasploit.py I have to chooce the network interface and I chooce "tun0" but when select it, the execution is stoped because it needs a MAC address and "tun0" doesn't have it.

What can I do?

**Comment by Vladimir-Ivanov-Git** [comment]
If network interface does not have a mac address set broadcast source mac.
https://github.com/Vladimir-Ivanov-Git/raw-packet/commit/750c9c056ce9eb30b23d2786845416af5bbaba79

**Comment by Vladimir-Ivanov-Git** [comment]
Ok?
